//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineLeaveManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int empId { get; set; }
        public string empName { get; set; }
        public string empType { get; set; }
        public string dept { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public int available { get; set; }
    }
}
