//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineLeaveManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaves1
    {
        public int R_no { get; set; }
        public int empId { get; set; }
        public string empName { get; set; }
        public string empType { get; set; }
        public string dept { get; set; }
        public string reason { get; set; }
        public int leaves { get; set; }
        public System.DateTime from { get; set; }
        public System.DateTime to { get; set; }
        public string status { get; set; }
    }
}
